version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'Build(deps)'
    labels:
      - dependencies
    groups:
      spring:
        patterns:
          - 'org.springframework.boot:*'
          - 'org.springframework.cloud:*'
          - 'org.springframework.security:*'
      grpc:
        patterns:
          - 'io.grpc:*'

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: 'Build(deps)'
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: 'Build(deps)'
    labels:
      - dependencies
