spring:
  profiles:
    active: local
  application:
    name: kirjaswappi-backend
  data:
    mongodb:
      autoIndexCreation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

resilience4j.retry:
  instances:
    globalRetry:
      maxRetryAttempts: 3
      waitDuration: 1000
      retryExceptions:
        - java.net.SocketTimeoutException
        - java.net.ConnectException
        - org.springframework.dao.OptimisticLockingFailureException
        - org.springframework.web.client.HttpServerErrorException