spring:
  profiles:
    active: local
  application:
    name: kirjaswappi-backend

server:
  port: 8080

resilience4j.retry:
  instances:
    globalRetry:
      maxRetryAttempts: 3
      waitDuration: 1000
      retryExceptions:
        - java.net.SocketTimeoutException
        - java.net.ConnectException
        - org.springframework.dao.OptimisticLockingFailureException
        - org.springframework.web.client.HttpServerErrorException