spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      autoIndexCreation: true
      uri: mongodb://localhost:27017/kirjaswappi
      database: kirjaswappi

server:
  port: 8080