spring:
  web:
    resources:
      add-mappings: false
  profiles:
    active: local
  application:
    name: KirjaSwappi-Backend
  messages:
    basename: messages.messages
    fallback-to-system-locale: false
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: smtp.zoho.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        debug: true
        smtp:
          from: ${EMAIL_USERNAME}
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.zoho.com
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        default:
          encoding: UTF-8

resilience4j.retry:
  instances:
    globalRetry:
      maxAttempts: 3
      waitDuration: 1000
      retryExceptions:
        - java.net.SocketTimeoutException
        - java.net.ConnectException
        - org.springframework.dao.OptimisticLockingFailureException
        - org.springframework.web.client.HttpServerErrorException
        - org.springframework.mail.MailSendException

logging:
  level:
    org:
      springframework:
        mail: DEBUG
        boot:
          actuate: DEBUG
        security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health
    endpoint:
      health:
        show-details: always