spring:
  config:
    activate:
      on-profile: cloud
  data:
    mongodb:
      autoIndexCreation: true
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}

springdoc:
  swagger-ui:
    schemes:
      - https

server:
  forward-headers-strategy: native
  port: 10000

s3:
  url: ${S3_URL}
  bucket: kirjaswappi
  accessKey: ${S3_ACCESS_KEY}
  secretKey: ${S3_SECRET_KEY}

jwt:
  secret: ${JWT_SECRET}
  expiration: 300000