spring:
  web:
    resources:
      add-mappings: false
  profiles:
    active: local
  application:
    name: KirjaSwappi-Backend
  messages:
    basename: messages.messages
    fallback-to-system-locale: false
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    from-email: ${EMAIL_FROM}
    properties:
      mail:
        debug: false
        default:
          encoding: UTF-8
        smtp:
          from: ${EMAIL_USERNAME}
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: ${EMAIL_HOST}
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


resilience4j.retry:
  instances:
    globalRetry:
      maxAttempts: 3
      waitDuration: 1000
      retryExceptions:
        - java.net.SocketTimeoutException
        - java.net.ConnectException
        - org.springframework.dao.OptimisticLockingFailureException
        - org.springframework.web.client.HttpServerErrorException
        - org.springframework.mail.MailSendException

logging:
  level:
    com.kirjaswappi.backend.jpa.repositories.CustomBookRepositoryImpl: DEBUG
    org:
      springframework:
        mail: DEBUG
        boot:
          actuate: DEBUG
        security: DEBUG

google:
  api:
    clientId: 43921547457-06chtojpprgds80g1gq5tprmn5qg0hmq.apps.googleusercontent.com

notification:
  service:
    host: ${NOTIFICATION_SERVICE_HOST:notify.kirjaswappi.fi}
    port: ${NOTIFICATION_SERVICE_PORT:50051}

management:
  endpoints:
    web:
      exposure:
        include: health
    endpoint:
      health:
        show-details: always