spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      autoIndexCreation: true
      uri: mongodb://localhost:27017/kirjaswappi
      database: kirjaswappi
  mail:
    host: smtp.example.com
    port: 587
    username: test@example.com
    password: test
    from-email: test@example.com
    properties:
      mail:
        smtp:
          from: test@example.com
          ssl:
            trust: smtp.example.com

server:
  port: 8080

s3:
  url: http://localhost:9000
  bucket: kirjaswappi
  accessKey: test
  secretKey: test

jwt:
  secret: abcdefghijklmnopqrstuvwxyz1234567890
  expiration: 300000