spring:
  config:
    activate:
      on-profile: cloud
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}

springdoc:
  swagger-ui:
    schemes:
      - https

server:
  forward-headers-strategy: native