spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      autoIndexCreation: true
      uri: mongodb://localhost:27017/kirjaswappi
      database: kirjaswappi

server:
  port: 8080

s3:
  url: http://localhost:9000
  bucket: kirjaswappi
  accessKey: test
  secretKey: test