name: Check & deploy API documentation

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-openapi:
    name: Generate OpenAPI spec (via Maven plugin)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Generate OpenAPI spec
        run: mvn clean compile springdoc-openapi:generate

      - name: Upload OpenAPI artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi-doc
          path: doc/api-documentation.yml

  deploy-doc:
    if: ${{ github.event_name == 'push' }}
    needs: generate-openapi
    name: Deploy API documentation on Bump.sh
    runs-on: ubuntu-latest
    steps:
      - name: Download OpenAPI artifact
        uses: actions/download-artifact@v4
        with:
          name: openapi-doc
          path: doc/

      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        with:
          doc: openapi
          token: ${{ secrets.BUMP_TOKEN }}
          file: doc/api-documentation.yml

  api-diff:
    if: ${{ github.event_name == 'pull_request' }}
    needs: generate-openapi
    name: Check API diff on Bump.sh
    runs-on: ubuntu-latest
    steps:
      - name: Download OpenAPI artifact
        uses: actions/download-artifact@v4
        with:
          name: openapi-doc
          path: doc/

      - name: Comment pull request with API diff
        uses: bump-sh/github-action@v1
        with:
          doc: openapi
          token: ${{ secrets.BUMP_TOKEN }}
          file: doc/api-documentation.yml
          command: diff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
