name: PR Pipeline

permissions:
  contents: read
  pull-requests: write

on: pull_request

jobs:
  test_and_coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'sapmachine'
          java-version: '21'

      - name: Run Tests and Generate Coverage Report
        run: mvn test jacoco:report -Dspring.profiles.active=cloud
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
          S3_URL: ${{ secrets.S3_URL }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Generate JaCoCo badge and summary
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          badges-directory: badges
          generate-branches-badge: true
          generate-summary: true

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

      - name: Install GitHub CLI and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq

      - name: Comment on PR with coverage percentages
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          REPORT=$(<badges/coverage-summary.json)
          RAW_COVERAGE=$(jq -r '.coverage' <<< "$REPORT")
          RAW_BRANCHES=$(jq -r '.branches' <<< "$REPORT")
          COVERAGE=$(printf "%.1f%%" "$RAW_COVERAGE")
          BRANCHES=$(printf "%.1f%%" "$RAW_BRANCHES")
          NEWLINE=$'\n'
          BODY="## ✅  Test Coverage Summary${NEWLINE}* __Coverage:__ ${COVERAGE}${NEWLINE}* __Branches:__ ${BRANCHES}"
          gh pr comment ${{ github.event.pull_request.number }} --body "${BODY}" --edit-last --create-if-none
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
