name: PR Pipeline

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    container: maven:3-sapmachine-17
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run Spotless Check
      run: mvn spotless:apply

    - name: Run Build Package
      run: mvn clean package -DskipTests