name: PR Pipeline

on: pull_request

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: maven:3-sapmachine-21
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run Build Package
      run: mvn clean package -DskipTests

    - name: Run Tests
      run: mvn test -Dspring.profiles.active=cloud
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
        S3_URL: ${{ secrets.S3_URL }}
        S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
        S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}